name: CI
on: [push]
jobs:

  ubuntu-build:
    name: Ubuntu build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        run: go build -v -i -o cstest .

      - name: Running the tests
        run: |
          ./cstest -help
          ./cstest --help
          ./cstest -config tests/positive0/config.json
          ./cstest -config tests/positive1/config.json
          ./cstest --config=tests/positive1/config.json
          ./cstest --config=tests/positive2/config.json
          ./cstest --config=tests/positive3/config.json

      - name: Create package
        run: |
          tar cvzf cstest-linux.tar.gz cstest

      - name: Upload package
        uses: actions/upload-artifact@v1.0.0
        with:
#          name: cstest-linux.tar.gz
#          path: cstest.tar.gz
          name: cstest-linux
          path: cstest

      - name: Create GitHub draft release (if it's tagged build)
        uses: softprops/action-gh-release@00c56dd770930df82f15d1a9797e9ed3ce054da7
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: cstest-linux.tar.gz
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows-build:
    name: Windows build
    runs-on: windows-latest
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: echo stub

      - name: Build
        run: go build -v -i -o cstest.exe .

      - name: Running the tests
        run: |
          cstest.exe -help
          cstest.exe --help
          cstest.exe -config tests/positive0/config.json
          cstest.exe -config tests/positive1/config.json
          cstest.exe --config=tests/positive1/config.json
          cstest.exe --config=tests/positive2/config.json
          cstest.exe --config=tests/positive3/config.json

      - name: Create package
        run: |
          7z.exe a -tzip -r cstest-windows.zip cstest.exe

      - name: Upload package
        uses: actions/upload-artifact@v1.0.0
        with:
#          name: cstest-windows.zip
#          path: cstest.zip
          name: cstest-windows
          path: cstest.exe

      - name: Create GitHub draft release (if it's tagged build)
        uses: softprops/action-gh-release@00c56dd770930df82f15d1a9797e9ed3ce054da7
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: cstest-windows.zip
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macOS-build:
    name: MacOS build
    runs-on: macOS-latest
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        run: go build -v -i -o cstest .

      - name: Running the tests
        run: |
          ./cstest -help
          ./cstest --help
          ./cstest -config tests/positive0/config.json
          ./cstest -config tests/positive1/config.json
          ./cstest --config=tests/positive1/config.json
          ./cstest --config=tests/positive2/config.json
          ./cstest --config=tests/positive3/config.json

      - name: Create package
        run: |
          tar cvzf cstest-macOS.tar.gz cstest

      - name: Upload package
        uses: actions/upload-artifact@v1.0.0
        with:
#          name: cstest-macOS.tar.gz
#          path: cstest.tar.gz
          name: cstest-macOS
          path: cstest

      - name: Create GitHub draft release (if it's tagged build)
        uses: softprops/action-gh-release@00c56dd770930df82f15d1a9797e9ed3ce054da7
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: cstest-macOS.tar.gz
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
